### ISSUE TITLE
Write a GitLab full CI

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#362]
Ideally `__site` would be ignored by `.git` locally and generated on GitHub / GitLab, this may also  help avoid the crap with `dev` branch and `master` branch on GitHub for personal/org websites.

On GitLab it should be pretty straightforward using an adapted version of  https://gitlab.com/tkpapp/GitlabJuliaDemo.jl 

On GitHub it's a bit more complicated but we can make use of
- https://github.com/julia-actions/setup-julia
- massage https://github.com/JamesIves/github-pages-deploy-action/blob/dev/src/git.ts into doing what we want

**Comment by cserteGT3** [comment]
I don't know much about docker, but wanted to create an image with julia and related packages (Franklin, PlotlyJS, etc.) to be able to commit only the source of a site, and then CI would take care of everything else.
Still planning to do this, though it's primarily for myself to learn more about docker and CI. (A blog post is also planned, but need to do the whole thing in the first place 😄).
It would may help to spread Franklin as well 😉

**Comment by tlienart** [comment]
Cool yes! I'm not planning to work on this any time soon so whatever you come up with will surely be useful 😄

**Comment by tlienart** [comment]
For GitHub, #379 is where it's add, I'm reasonably confident it will be done soon.

**Comment by fbanning** [comment]
> On GitLab it should be pretty straightforward using an adapted version of https://gitlab.com/tkpapp/GitlabJuliaDemo.jl

Ahoy, has there been any progress on this? I've not worked with GitLab CI before but would love to have a simple integration out of the box. Currently I run `serve()`, `verify_links()`, `optimize()` and then push the new `__site` folder to the repo every time someone updates the website. It's not a big issue but still a bit tedious so I'd love an automated approach. :)

**Comment by tlienart** [comment]
yes it should be that easy, basically you should have something that looks like this: https://github.com/tlienart/FranklinTemplates.jl/blob/45f1e32bb71740921c43fc5b63a592de26fe76e2/src/templates/common/.github/workflows/deploy.yml#L35-L39

followed by the trick required to get stuff in the `public` folder that GitLab requires and which is already in the default `.gitlab-ci.yml` 

Please let me know how that goes and ping me from here if you encounter problems (also if you make it work as I could bring your stuff to the default gitlab script) thanks!

**Comment by tlienart** [comment]
So potentially something like

```
image: julia:1.5

before_script:
  # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
  - apt-get -qq update; apt-get -y install git

default:
  script:
    - julia --project=@. -e "using Pkg; Pkg.activate("."); Pkg.instantiate();
            using NodeJS; run(`$(npm_cmd()) install highlight.js`);
            using Franklin;
            optimize()"

pages:
    stage: deploy
    script:
        - mv __site public
    artifacts:
        paths:
            - public
    only:
        - master
```

I haven't tested this though so maybe give it a shot, see whether it works?

**Comment by fbanning** [comment]
That's pretty close to what I had in mind. I'll try it out and see if things work as expected. Will report back once I have some news. :)

**Comment by fbanning** [comment]
> ```using NodeJS; run(`$(npm_cmd()) install highlight.js`);```

I've encountered some problems with this line throwing the following error:

```
/bin/bash: command substitution: line 116: syntax error near unexpected token `)'
/bin/bash: command substitution: line 116: `npm_cmd())'
ERROR: MethodError: no method matching run()
Closest candidates are:
  run(!Matched::Base.AbstractCmd, !Matched::Any...; wait) at process.jl:437
Stacktrace:
 [1] top-level scope at none:1
Cleaning up file based variables
ERROR: Job failed: exit code 1
```

Replacing the `""` in the julia comand with `''` seems to have fixed the problem for me. Not 100% sure about this though.

Other than that, things seem to be in working order and GitLab says that the yaml file is valid (which is a good sign by itself).

However, I think it's necessary to actually add `serve()` with the correct kwargs. Normally `serve()` runs in the REPL until cancelled but we want it to run only once to create the new page files and afterwards stop the liveserver. I've tried out `serve(single=true, is_final_pass=true)` which afaict should to do the trick.

So this is what my `.gitlab-ci.yml` looks like right now:

```yaml
image: julia:1.5

before_script:
  - apt-get -qq update; apt-get -y install git

default:
  script:
    - julia --project=@. -e 'import Pkg; Pkg.instantiate();
        using NodeJS; run(`$(npm_cmd()) install highlight.js`);
        using Franklin;
        serve(single=true, is_final_pass=true);
        optimize()'

pages:
    stage: deploy
    script:
        - mv __site public
    artifacts:
        paths:
            - public
    only:
        - master
```

While the `default` job succeeds, the `pages` job fails with the following message:

```
$ mv __site public
mv: cannot stat '__site': No such file or directory
Cleaning up file based variables
ERROR: Job failed: exit code 1
```

Any ideas? Hm... Maybe it's a problem that we've separated the `default` and the `pages` jobs and GitLab cleans up temporary files (like `__site/`) after the job has finished?

Now let's try the following:

```yaml
image: julia:1.5

before_script:
  - apt-get -qq update; apt-get -y install git

pages:
  stage: deploy
  script:
    - julia --project=@. -e 'import Pkg; Pkg.instantiate();
      using NodeJS; run(`$(npm_cmd()) install highlight.js`);
      using Franklin;
      serve(single = true, is_final_pass = true);
      optimize()'
    - mv __site public
  artifacts:
    paths:
      - public
  only:
    - master
```

Et voilà, c'est ça! A very simple GitLab CI yml file that does what we want it to do. 😄

(Should I make a PR out of this?)
