### ISSUE TITLE
Scaling figures

### ISSUE THREAD

**Issue by snirgaz** [tlienart/Franklin.jl#437]
Is it possible to "scale" SVG figures?
It would be nice to extend \fig to allow for scaling centering etc.

Thanks!

**Comment by tlienart** [comment]
Right so I guess the easiest way is to just use CSS for this.

### Easy way

In the Markdown

```markdown
@@im-50
![](/assets/rndimg.jpg)
@@
```

In the CSS:

```css
.im-50 {text-align: center;}
.im-50 img {
    padding: 0;
    width: 50%;
}
```

(padding 0 is because you might already have some padding set if you're using one of the default CSS templates)

### More complex way

As a partial step towards #62 where you may wish for a latex like:

```latex
\begin{figure}
\includegraphics[.5\textwidth]{/assets/rndimg.jpg}
\caption{The caption}
\end{figure}
```

You could put the following (or a version) in the config:

```markdown
\newcommand{\figenv}[3]{
~~~
<figure style="text-align:center;">
<img src="!#2" style="padding:0;#3" alt="#1"/>
<figcaption>#1</figcaption>
</figure>
~~~
}
```

(note the `!#` is to avoid the insertion of extra whitespaces, this is usually good for paths, not necessary here but good practice if you use latex-like commands for paths in franklin, see the docs on commands). 

and you can use this as

```
\figenv{the caption}{/assets/rndimg.jpg}{width:50%;border: 1px solid red;}
```

I'm hoping this is reasonably self-explanatory 😄 

<img width="741" alt="Screen Shot 2020-04-02 at 08 47 43" src="https://user-images.githubusercontent.com/10897531/78218808-af302e00-74be-11ea-98b5-635f830dac6a.png">

**Comment by tlienart** [comment]
PS: of course this works with SVG too, try

```
\figenv{the caption}{https://upload.wikimedia.org/wikipedia/commons/6/67/Firefox_Logo%2C_2017.svg}{width:50%;border: 1px solid red;}
```

<img width="379" alt="Screen Shot 2020-04-02 at 08 50 53" src="https://user-images.githubusercontent.com/10897531/78219052-1948d300-74bf-11ea-89aa-9523f5e303e3.png">

**Comment by snirgaz** [comment]
Excellent! Thanks!
The only thing I am missing is LaTeX like labeling (with automatic enumeration).
Your package is amazing BTW!

**Comment by tlienart** [comment]
Thanks for the positive feedback 😄 

Re labeling, there is `\label` which gives you the possibility to put an anchor. Try this on your page


```
Some place you will want to point to later \label{anchor name}.

(...)

Here you want to point to ![earlier](#anchor_name).
```

Actually automatic numbering of (I'm assuming) figures is also possible; you can just imitate how it's done for KaTeX; consider the following CSS for KaTeX numbering:

```css
body { counter-reset: eqnum; }

.katex { font-size: 1em !important; }

.katex-display .katex {
    display: inline-block; } /* overwrite katex settings */

.katex-display::after {
    counter-increment: eqnum;
    content: "(" counter(eqnum) ")";
    position: relative;
    float: right;
    padding-right: 5px; }
```

So basically here it starts a counter `eqnum` and every time it sees an equation it increments it, the rest is just the placement of the counter.

In your case you'd want to add a `fignum` and every time it sees a figure, it increments it, and then some placement of that counter in `figure` objects (or possibly `figure caption`). I actually believe you can even do the latex-like dependent numbering where you get a `1.1, 1.2` then `2.1`, `2.2` with this technique. But that may be a bit overkill for a single webpage :-) IMO webpages should not be that long 🤷‍♂
