### ISSUE TITLE
scale image and sub-list?

### ISSUE THREAD

**Issue by feima0011** [tlienart/Franklin.jl#501]
how to add an image to be a specific size to a webpage? 

and how to insert a multiple level list ?

**Comment by tlienart** [comment]
Hello!

### image size 

head to the `_css/franklin.css` folder and look for `img`  you will see the catch all 

```css
.franklin-content img {
    width: 70%;
    text-align: center;
    padding-left: 10%; }

.franklin-content .img-small img {
    width: 50%;
    text-align: center;
    padding-left: 20%; }
```

change that as you would like, possibly add a new rule like for instance 

```
.franklin-content .img-medium img {
 ...
}
```

which you can apply in your markdown by doing

```
@@img-medium ![](/path/to/image.png) @@
```

### sublist

Did you try

```
* item
  * subitem
* other item
  * other subitem
    * sub-sub item
```

otherwise, if that doesn't quite match what you want, you can always plug your own HTML in there to match exactly what you would  like (it shouldn't be necessary but it's always possible)

```
Some markdown
~~~
<ul>
<li>some item</li>
<ul>
<li>some  subitem</li>
</ul>
</ul>
~~~
Some more markdown
```

Hope this helps!
