### ISSUE TITLE
How to build the __site locally and deploy on GitHub as a project?

### ISSUE THREAD

**Issue by yenson-lau** [tlienart/Franklin.jl#816]
I think this is a very desirable feature. For example, if I generate some complex plots for my websites using a variety of Julia packages, I don't want GitHub to have to reinstall all the packages from scratch and rebuild the code every time. Instead I already have a completely built `__site` directory that should be directly deployable.

The problem with the project page, of course, comes down to the `prepath`. Although I've set the prepath, removed `__site` from my .gitignore, and ran the following code on my own computer

```julia
using Pkg; Pkg.activate("."); Pkg.instantiate();
using NodeJS; run(`$(npm_cmd()) install highlight.js`);
using Franklin;
optimize()
```

and I've replaced my GitHub action as follows

```
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: __site
```

I still couldn't get the site to deploy correctly. Is there any way for me to build the correct site on my own computer? Thanks!
