### ISSUE TITLE
Rendering and deploying previews using GitHub

### ISSUE THREAD

**Issue by Saransh-cpp** [tlienart/Franklin.jl#980]
Xref: https://github.com/FluxML/fluxml.github.io/pull/145

Is it possible to use GH pages instead of Netlify to deploy documentation previews with `Franklin`? The [documentation](https://franklinjl.org/workflow/deploy/#previewing_pull_requests) states -

> Now for the final step, you will need to visualize the obtained previews. Since Github only allow you to deploy one branch, you will need an alternative like Netlify. Create an account on [Netlify.com](https://www.netlify.com/), add your repository and chose the gh-preview branch without any additional settings. Set your Netlify website to be {netlify name}.netlify.app.

But, `Documenter.jl` already provides us with the "preview" feature using GH pages. This is due to the fact that Documenter.jl stores both the previews and the actual build in the same branch - `gh-pages`. For example see the [gh-pages branch](https://github.com/FluxML/Flux.jl/tree/gh-pages) branch of `Flux`. The branch has a directory named `previews` to store the previews.

Ideally the following should work, but will it? -
```yaml
- name: Fix URLs for PR preview deployment (pull request previews)
  if: github.event_name == 'pull_request'
  run: |
    echo "PREVIEW_FRANKLIN_WEBSITE_URL=https://fluxml.ai/previews/PR${{ github.event.number }}/" >> $GITHUB_ENV
    echo "PREVIEW_FRANKLIN_PREPATH=previews/PR${{ github.event.number }}" >> $GITHUB_ENV
- name: Deploy (preview)
  if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name # if this build is a PR build and the PR is NOT from a fork
  uses: JamesIves/github-pages-deploy-action@releases/v3
  with:
      BRANCH: gh-pages # The branch where the PRs previews are stored
      FOLDER: __site
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_FOLDER: "previews/PR${{ github.event.number }}" # The website preview is going to be stored in a subfolder
  - name: Deploy (main)
  if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
  uses: JamesIves/github-pages-deploy-action@releases/v3
  with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: gh-pages # Replace here the branch where your website is deployed
      FOLDER: __site
```
